#!/bin/zsh

# Define your array of paths
dirs=(
  ~/.local/scripts
  ~/.local/dev
  ~/Documents/Obsidian\ Vaults/Brain
)

# Help message function
show_help() {
    echo -e "\n[${INFO}INFO${RESET}]: Usage Examples"
    echo -e "  -h, --help    # Show this help message"
    echo -e "  <no args>     # Commit and push changes in all directories"
    echo -e "  status        # Show git status for all repositories"
    echo -e "\nConfigured directories:"
    for dir in "${dirs[@]}"; do
        echo "  - $dir"
    done
    echo
}

# Iterate over each directory
if [[ $# -eq 0 ]]; then
    for dir in ${dirs[@]}; do
        if [[ -d "$dir" ]]; then
            pushd -q "$dir" || continue
            echo -e "\n[${INFO}INFO${RESET}]: Processing: $dir\n"
            git add .
            git commit -m 'automated commit'
            git push
            popd -q
        else
            echo "Directory not found: $dir"
        fi
    done
elif [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
elif [[ $1 -eq "status" ]]; then
    for dir in ${dirs[@]}; do
        if [[ -d "$dir" ]]; then
            pushd -q "$dir" || continue
            echo -e "\n[${INFO}INFO${RESET}]: Processing: $dir\n"
            git status
            popd -q
        else
            echo "Directory not found: $dir"
        fi
    done
fi