#!/bin/zsh

arg1=$1
arg2=$2
scripts_pwd=$HOME/Projects/terminal_scripts

if [[ "$arg1" = "-h" || "$arg1" = "--help" ]]; then
    echo
    echo "[Info] For shortcutting creating new scripts:"
    echo "opn [(-n) or (new)] [<name of new script>]"
    echo
    echo "Turn newly created scripts into executables:"
    echo "opn chmod [<name of script>]"
    echo
    echo "Available Scripts:"
    ls $scripts_pwd | grep -v README.md | sed 's/^/> /'
    echo
elif [[ "$arg1" = "-n" || "$arg1" = "new" ]]; then
    echo
    echo "[Info] Creating a new script for "$arg2...
    code $scripts_pwd/$arg2
elif [[ "$arg1" = "chmod" ]]; then
    if [[ -f "$arg2" ]]; then 
        echo
        echo "[Info] Turning '$arg2' into an executable file..."
        chmod +x "$scripts_pwd/$arg2"
        if [[ $? -eq 0 ]]; then 
          echo "Successfully made '$arg2' executable."
        else
          echo "[Error] Failed to make '$arg2' executable."
        fi
    else
        echo "[Error] '$arg2' is not a file."
    fi
    echo
elif [[ ! -e "$scripts_pwd/$arg1" ]]; then
    echo
    echo "[Error] Script not found:"$scripts_pwd/$arg1
    echo
    echo "Valid aruments include:"
    ls $scripts_pwd | grep -v README.md | sed 's/^/> /'
    echo
else
    echo $scripts_pwd/$arg1
    code $scripts_pwd/$arg1
fi