#!/bin/bash

arg1=$1
arg2=$2
week='/Users/aaronpotter/Projects/CS50/week'$1'_'$2

echo
echo 'Adding new week directory to project...'
echo 
tree $week

mkdir $week
mkdir $week'/lecture'
mkdir $week'/pset'$1